### ISSUE TITLE
Provide sample of yaml entries

### ISSUE THREAD

**Issue by konradwalsh** [t0mer/manish-custom-notifier#1]
Thanks for the addon.

any chance you could post some sample entries?
```
notify:
  - platform: manish
    name: MaNish whatsapp notifire
    target: # WhatsApp number for notificatin (Without the + sign of the country_code)
    token: #T he token for the Whatsapp cloud API
    phone_number_id: #Phone number id from the Whatsapp cloud API
    template: # Template's name's to use
    language: # Template's language
```
For example
should language: be ` language: en_US `   or  `language: English (US)`

It would also be helpful to see a sample message that fills in the variables declared in the template
