### ISSUE TITLE
Notify does not work anymore with HA 2025.1.0

### ISSUE THREAD

**Issue by rqsnst** [t0mer/manish-custom-notifier#3]
i updated zu HA 2025.1.0
and noticed that the notification does not work anymore

i get in the logs this error:
Error executing script. Service not found for call_service at pos 1: Action notify.christiane not found

in configuration.yalm i defined this:

```
notify:
    - platform: manish
    name: Christiane
    target: 49xxxxxxx # WhatsApp number for notificatin (Without the + sign of the country_code)
    token: !secret token_whatsapp #T he token for the Whatsapp cloud API
    phone_number_id: xxxxxxx #Phone number id from the Whatsapp cloud API
    template: ha_christiane # Template's name's to use
    language: de # Template's language
```

before the update everthing worked very well.

can someone check what is to do after updating to HA 2025.1.0
